blogpost/urls.py
from django.urls import path

from blogpost.apps import NewappConfig
from blogpost.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = NewappConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_confirm, GeneratePasswordView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email_confirm/<str:token>/', email_confirm, name='email_confirm'),
    path('reset_password/', GeneratePasswordView.as_view(template_name='reset_password.html'),
         name='reset_password')
]

blogpost/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    content = models.TextField(verbose_name='Описание')
    slug = models.CharField(max_length=150, verbose_name='Slug', null=True, blank=True)
    preview = models.ImageField(upload_to='blogentry/photo', verbose_name='Изображение', null=True, blank=True)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    sign_publication = models.IntegerField(default=0, verbose_name='Просмотры')
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blogpost/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blogpost.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('blogpost:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview',)
    success_url = reverse_lazy('blogpost:list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blogpost:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.sign_publication += 1
        self.object.save()

        if self.object.sign_publication >= 100:
            self.send_notification()

        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogpost:list')

blogpost/templates/blogpost/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <p>Хотите удалить Блог "{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'blogpost:list'%}" type="submit" class="btn btn-warning">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogpost/templates/blogpost/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
              <img src="{{blog.preview | media_filter }}" >
              <div class="card-body">
              <h2 class="card-text">{{ blog.title }}({{ blog.slug }})</h2>
                  <p class="card-text">{{ blog.content }}. </p>
                  <p class="card-text">Дата публикации {{ blog.created_at }}</p>
                  <p class="card-text">Просмотры {{ blog.sign_publication }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blogpost:list' %}">Назад</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

blogpost/templates/blogpost/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogpost/templates/blogpost/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Blogpost</h1>
</div>
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="{% url 'blogpost:create'%}" role="button">Создать Блог</a>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <img src="{{object.preview | media_filter }}">
                    <div class="card-body">
                        <h3 class="card-text">{{ object }}</h3>
                        <p class="card-text">{{ object.description | slice:100 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blogpost:view' object.pk %}"
                                   role="button">Подробнее</a>
                                <a class="btn btn-warning" href="{% url 'blogpost:edit' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'blogpost:delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}